server:
  port: 8001

spring:
  application:
    name: eureka_client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true                                 #访问路径可以显示IP地址
    instance-id: eureke_client8001                          #自定义服务名称信息

info:
  app.name: eureka_client
  company.name: com.alteza
  build.artifactId: $project.artifactId$
  build.version: $project.version$